version: '2'
services:
  newwsfeedapp:
    build: ./
    restart: on-failure
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - testpostgres
  testpostgres:
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=@postgres.user@
      - POSTGRES_PASSWORD=@postgres.password@
      - POSTGRES_DB=@postgres.db@